export interface ServerProfile {
  serverName: string
  gameVersion: string
  coreType: string
  coreName?: string
}

export const SERVER_PROFILE_FILE = 'profilemcsrv.toml'

function escapeToml(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export function serializeServerProfile(profile: ServerProfile): string {
  const lines = [
    '# Generated by MCServerTools',
    `server_name = "${escapeToml(profile.serverName)}"`,
    `game_version = "${escapeToml(profile.gameVersion)}"`,
    `core_type = "${escapeToml(profile.coreType)}"`,
  ]

  if (profile.coreName) {
    lines.push(`core_name = "${escapeToml(profile.coreName)}"`)
  }

  return `${lines.join('\n')}\n`
}

function unquoteToml(value: string): string {
  const trimmed = value.trim()
  if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
    return trimmed.slice(1, -1).replace(/\\"/g, '"').replace(/\\\\/g, '\\')
  }
  return trimmed
}

export function parseServerProfile(text: string): Partial<ServerProfile> {
  const result: Partial<ServerProfile> = {}

  for (const line of text.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue

    const eqIndex = trimmed.indexOf('=')
    if (eqIndex === -1) continue

    const key = trimmed.slice(0, eqIndex).trim()
    const value = unquoteToml(trimmed.slice(eqIndex + 1))

    if (key === 'server_name') result.serverName = value
    if (key === 'game_version') result.gameVersion = value
    if (key === 'core_type') result.coreType = value
    if (key === 'core_name') result.coreName = value
  }

  return result
}

